// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Movie struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type NewMovie struct {
	Name string `json:"name"`
}
